name: "Build and Preview"

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

permissions:
  contents: write
  pull-requests: write

concurrency: preview-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Make sure it builds. Then show a preview.
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'
      - name: Cache dependencies
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run build:preview
        env:
          VITE_BASE_PATH: "/Gyros/pr-preview/pr-${{ github.event.pull_request.number }}/"
      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        if: github.event.pull_request.head.repo.full_name == github.repository
        with:
          source-dir: ./dist/
